### ISSUE TITLE
JavaScript Error bei Vorlage BW mit Störer

### ISSUE THREAD

**Issue by JanMalte** [codeispoetry/sharepicgenerator#330]
https://sharepicgenerator.de/bw

```
bw.min.js?v=1678090760:953 Uncaught ReferenceError: countLines is not defined
    at Object.draw (bw.min.js?v=1678090760:953:47)
    at eval (eval at setColor (main.min.js?v=1678090760:1:6822), <anonymous>:1:5)
    at HTMLSpanElement.setColor (main.min.js?v=1678090760:1:6822)
    at HTMLSpanElement.dispatch (jquery.min.js:2:43336)
    at y.handle (jquery.min.js:2:41320)

bw.min.js?v=1678090760:953 Uncaught ReferenceError: countLines is not defined
    at HTMLInputElement.draw (bw.min.js?v=1678090760:953:47)
    at HTMLInputElement.dispatch (jquery.min.js:2:43336)
    at y.handle (jquery.min.js:2:41320)
```

Quelltext: https://github.com/codeispoetry/sharepicgenerator/blob/f73c3c73b5458ca34c00b72bf31d9b1e6e9c2c27/code/build/js/bw/76eyecatcherpin.js#L50

Fehlt ggf. einfach die Zeile aus dem `radentscheid` tenant?
```javascript
const countLines = ($('#pintext').val().match(/\n/g) || []).length; // start with 0
```
Quelle: https://github.com/codeispoetry/sharepicgenerator/blob/f73c3c73b5458ca34c00b72bf31d9b1e6e9c2c27/code/build/js/radentscheid/76eyecatcherpin.js#L24

**Comment by codeispoetry** [comment]
Dankeschön für den Hinweis. Ist gefixt.
